name: CI WAS Scan
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tenablescan:
    name: was-cicd-testing
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello test
        run: |
          echo "Hello World"
      - name: Test Pre-defined action
        uses: EvanGrace25/10ble-was-cicd-action@main
        with:
          access_key: ${{ secrets.ACCESS_KEY }}
          secret_key: ${{ secrets.SECRET_KEY }}
          link_container: petstore
          use_petstore_example: true
